version: '3.8'

services:
  nestjs-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./main.ts: /nestjs-server/main.ts
      - ./src: /nestjs-server/src
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks: — api
    env_file:
      - .env.docker

  postgres:
    image: postgres:16
    container_name: postgresprisma
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.docker
    volumes:
      - /data/postgres: /var/lib/postgresql/data

networks:
  api:
volumes:
  postgres:
    name: nest-prisma-docker-db
